
public class ID {
	// entity ID
	public static final int PLAYER = 0, ITEM = 1, TREE = 2, ROCK = 3, COW = 4, BACKGROUND = 5, CRAFTING_TABLE = 6, FURNACE = 7, WARDROBE = 8, FLOOR = 9, WALL = 10, ORE = 11, METALWALL = 12, SHOP = 13, BED = 14, CRYSORE = 15, WORKBENCH = 16, EVAORE = 17, POISONSHROOM = 18, CHEST = 19;

	// item ID
	public static final int NOTHING = 0, WOOD = 1, STONE = 2, FOOD = 3, COOKED_FOOD = 4, ITEMFURN = 5, ITEMWARD = 6, ITEMFLOOR = 7, ITEMWALL = 8, OREITEM = 9, STEEL = 10, ITEMMWALL = 11, COIN = 12, BEDITEM = 13, REVIVALTOTEM = 14, WOODPICK = 15, STONEPICK = 16, CLUB = 17, STEELPICK = 18, STEELARMOR = 19, STEELSWORD = 20, CRYSTAL = 21, MINELADDER = 22, ITEMWB = 23, WIRE = 24, BATTERY = 25, DRILL = 26, CIRCUITBOARD = 27, AUTODRILL = 28, EVANITEORE = 29, SHROOMS = 30, EVANITE = 31, EVASWORD = 32, EVAPICK = 33, EVAARMOR = 34, CHESTITEM = 35;
	public static final String[] itemNames = {
		"NOTHING",
		"WOOD",
		"STONE",
		"FOOD",
		"COOKED FOOD",
		"FURNACE",
		"WARDROBE",
		"FLOOR",
		"WALL",
		"ORE",
		"STEEL",
		"METAL WALL",
		"COIN",
		"BED",
		"REVIVAL TOTEM",
		"WOOD PICK",
		"STONE PICK",
		"CLUB",
		"STEEL PICK",
		"STEEL ARMOR",
		"STEEL SWORD",
		"CRYSTAL",
		"MINE LADDER",
		"WORKBENCH",
		"WIRE",
		"BATTERY",
		"DRILL",
		"CIRCUIT BOARD",
		"AUTO DRILL",
		"EVANITE ORE",
		"SHROOMS",
		"EVANITE",
		"EVANITE SWORD",
		"EVANITE PICK",
		"EVANITE ARMOR",
		"CHEST",
	};

	// recipe ID
	public static final int CRAFTFURN = 0, CRAFTWARD = 1, CRAFTFLOOR = 2, CRAFTWALL = 3, CRAFTMWALL = 4, CRAFTWOODPICK = 5, CRAFTSTONEPICK = 6, CRAFTCLUB = 7;
	// cook ID
	public static final int COOKFOOD = 0, COOKMETAL = 1, COOKSTEELPICK = 2, COOKSTEELARMOR = 3, COOKSTEELSWORD = 4, COOKWORKBENCH = 5, COOKEVANITE = 6;
	// workbench ID
	public static final int WB_WIRE = 0, WB_BATTERY = 1, WB_DRILL = 2, WB_CBOARD = 3, WB_AUTODRILL = 4, WB_EVASWORD = 5, WB_EVAPICK = 6, WB_EVAARMOR = 7, WB_CHEST = 8;

	// dimension ID
	public static final int OVERWORLD = 0, MINES = 1, DEEPMINES = 2;
}
